### ISSUE TITLE
表单数据提交时做有无修改的判断

### ISSUE THREAD

**Issue by Onesimu** [d2-projects/d2-crud#13]
点击确定按钮提交表单时, 不会检查数据是否修改吗, 好像没有任何改动直接点确定, 表单也提交了. 如果要加判断的话有没有什么思路呢? 望指点 谢谢

**Comment by sunhaoxiang** [comment]
只有调用done()之后表单才会提交，因此可以在row-edit事件中，加入自己的逻辑，之后再看情况是否调用done()
