### ISSUE TITLE
pagination能否支持传入Total

### ISSUE THREAD

**Issue by datoulei** [d2-projects/d2-crud#15]
我想请问下pagination里的total使用data的length是出于什么考虑呢？如果后端接口请求的是分页数据，那分页组件就没法工作了。

**Comment by sunhaoxiang** [comment]
后端的分页需要自己封装

**Comment by sunhaoxiang** [comment]
pagination会进行重构，暴露接口用来和后端对接

**Comment by Dean-ZhenYao-Wang** [comment]
this.pagination.total = res.page.total
按例子写的，但是这样实际并无任何效果

> pagination会进行重构，暴露接口用来和后端对接

this.pagination.total = res.page.total
按例子写的，但是这样实际并无任何效果
