### ISSUE TITLE
column里的component在指定诸如el-switch之后，如何监听切换事件？

### ISSUE THREAD

**Issue by terranc** [d2-projects/d2-crud#16]
rt

**Comment by terranc** [comment]
如果不能监听到数据变化，那不是用自定义组件而用el-input、el-switch……就没啥用吧，能具体指北一下不，最佳实践啥样子

**Comment by sunhaoxiang** [comment]
默认可以使用的组件功能比较单一，是为了简单需求制作的，复杂的就需要使用自定义组件自己封装逻辑，参考示例中的自定义组件部分

**Comment by FairyEver** [comment]
[https://d2admin.fairyever.com/#/demo/d2-crud/demo25](https://d2admin.fairyever.com/#/demo/d2-crud/demo25)

**Comment by terranc** [comment]
@sunhaoxiang @FairyEver 自定义的话我知道是可以，但很多时候其实我们只是需要一个诸如el-switch就可以了，从业务上来说没必要去封装了，如果只是为了想要对switch切换之后的值的变化去做进一步的处理，比如切换之后提交个ajax请求。

我其实主要是对文档中说可以用el-input、el-switch等这些element ui自带的组件，但又用了之后又无法对其值的数据变化写进一步的逻辑，那什么场景会需要这么用呢，因为这些表单里用的组件主要不就是为了修改数据用的吗。

**Comment by magicdvd** [comment]
@terranc  修改el-switch/el-*, 会触发d2-data-change 事件。只不过是全部table绑定的data数据返回，可以变通的处理很不方便
@FairyEver 既然有@row-edit 这个事件，建议优化触发这个事件就可以处理了。这是行级处理
