### ISSUE TITLE
增加和编辑表单时的按钮标题和样式

### ISSUE THREAD

**Issue by JarlRyan** [d2-projects/d2-crud#2]
`<div slot="footer">
        <el-button
        :size="$d2CrudSize ? Object.assign({ saveButtonSize: $d2CrudSize}, formOptions) : null"
        :type="formOptions ? handleAttribute(formOptions.saveButtonType, null) : null"
        :icon="formOptions ? handleAttribute(formOptions.saveButtonIcon, null) : null"
        :loading="formOptions ? handleAttribute(formOptions.saveLoading, false) : false"
        @click="handleDialogSave"
      >
      确 定
      </el-button>
      </div>`

 这个确定能不能改成从外面自定义?

**Comment by sunhaoxiang** [comment]
1.2.0已实现
