### ISSUE TITLE
求支持每一行可以添加一个可以点击展开的slot，用于展示自有定制组件

### ISSUE THREAD

**Issue by mymmoonoa** [d2-projects/d2-crud#25]
求大神支持给每一行可以添加一个可以点击展开的slot，用于传递自有的定制组件。
效果如：
![screen shot 2018-11-21 at 7 20 46 pm](https://user-images.githubusercontent.com/650114/48838285-dce16f00-edc2-11e8-86e0-402a6b26c563.png)

**Comment by winter-ice** [comment]
+1

**Comment by Jkanon** [comment]
目前已经支持展开自定义组件的。
{
          key: 'xxx',
          type: 'expand',
          component: {
            // 这边的RowExpand就是自定义组件
            name: RowExpand,
            props: {
              // 这边可以传入自定义属性
              checkCallback:  this.xxx
            }
          }
        },

然后RowExpand组件至少接收两个参数
// 传入的字段数据
value: {
      required: true
    },
    // 可以通过scope.row来引用行数据
    scope: {
      type: Object,
      default: () => {}
    },
// 这个是上边传入的自定义属性
checkCallback: { type: Function }
