### ISSUE TITLE
建议行操作row-handle增加一些事件回调

### ISSUE THREAD

**Issue by magicdvd** [d2-projects/d2-crud#27]
简单场景： 创建用户， 需要 用户/密码/权限， 但是修改时候分开 密码和权限的修改，同时用户名无法修改。这需要add和edit template不同。
1.  row-add 和 row-edit 对应弹出的dialog 是调用同一个template. 是否支持各自对应模板。
2. 是否增加 @before-row-add  @before-row-edit 事件，在点击按钮弹出dialog前触发，这样可以动态修改dialog内容。
3. 表格内编辑，column使用components el-select等，修改后只触发了@d2-data-change,  强烈要求增加行级的修改触发，放入 @row-edit 是可以接受的，语义上是连贯的

以上这些我知道都可以custom组件自己来，但是既然提供了内置组件，我觉得加强下会便利很多。

**Comment by sunhaoxiang** [comment]
嗯，这个问题我已经在考虑了，预计会有一个大的更新，增加内置组件的事件监听，以及暴露更多的内部方法来操作表格，比如表格数据更新、模态框的开关、数据的增删改等等
