### ISSUE TITLE
row-handle里的confirm报错

### ISSUE THREAD

**Issue by mojie126** [d2-projects/d2-crud#34]
点击取消会提示：Uncaught (in promise) cancel

edit和remove都会...

**Comment by sunhaoxiang** [comment]
贴一下代码片段我看看吧

**Comment by mojie126** [comment]
内网...贴不出来...就是demo里的那段儿代码...

**Comment by sunhaoxiang** [comment]
你使用的vue和element版本分别是多少？

**Comment by mojie126** [comment]
vue:2.6.6
element:2.5.4

**Comment by sunhaoxiang** [comment]
好的， 我琢磨琢磨，应该是有个promise没处理异常

**Comment by mojie126** [comment]
是的，我自己写的都catch了...

**Comment by sunhaoxiang** [comment]
2.0.4已修复
