### ISSUE TITLE
如何导出excel或xls

### ISSUE THREAD

**Issue by dannykhoo** [d2-projects/d2-crud#4]
不好意思，我是新手，请问如何导出excel或xls呢？ 有没有具体教程，谢谢

**Comment by FairyEver** [comment]
可以自己结合 D2Admin 的导入导出插件：

导入 xlsx [https://d2-projects.github.io/d2-admin/#/demo/plugins/import/xlsx](https://d2-projects.github.io/d2-admin/#/demo/plugins/import/xlsx)

导出 [https://d2-projects.github.io/d2-admin/#/demo/plugins/export/table](https://d2-projects.github.io/d2-admin/#/demo/plugins/export/table)
