### ISSUE TITLE
表格多选功能不能设置默认值

### ISSUE THREAD

**Issue by AvnTwty** [d2-projects/d2-crud#43]
this.tableData.forEach(item => {
	if (item.check === 1) {
		this.$refs.d2Crud.$refs.elTable.toggleRowSelection(item, true)
	}
})
这段代码不能设置默认选中的项目，是在mounted里面调用的

**Comment by AvnTwty** [comment]
已解决；；

**Comment by AvnTwty** [comment]
this.$nextTick(() => {
				this.tableData.forEach((item, index) => {
					if (item.check === 1) {
						this.$refs.d2Crud.$refs.elTable.toggleRowSelection(item, true);
						this.$refs.d2Crud.updateRow(index, item)
					}
				})
			})

**Comment by AvnTwty** [comment]
已解决:
	this.$nextTick(() => {
				this.tableData.forEach((item, index) => {
					if (item.check === 1) {
						this.$refs.d2Crud.$refs.elTable.toggleRowSelection(item, true);
						this.$refs.d2Crud.updateRow(index, item)
					}
				})
			})

**Comment by mushu1990** [comment]
请问this.$refs.d2Crud.updateRow(index, item)的作用是什么呢？
我不加这句就出错了。
