### ISSUE TITLE
新增和编辑模板怎么修改title值

### ISSUE THREAD

**Issue by AvnTwty** [d2-projects/d2-crud#44]
this.$refs.d2Crud.addTemplate.属性名.title=‘名字’
this.addTemplate.属性名.title=‘名字’
这两种方法修改了title值，但是视图不能更新怎么处理呢？
如何手动修改模板的值？

**Comment by sunhaoxiang** [comment]
https://d2admin.fairyever.com/#/demo/d2-crud/demo16

**Comment by sunhaoxiang** [comment]
https://d2admin.fairyever.com/#/demo/d2-crud/demo17
