### ISSUE TITLE
nuxt 项目 2.0.5 升级到 2.1.0 报错

### ISSUE THREAD

**Issue by KevinFan520** [d2-projects/d2-crud#47]
![image](https://user-images.githubusercontent.com/12333291/57429448-bcb54780-725e-11e9-841a-7f7ee2eec893.png)
找到vendors.app.js:254 发现是以下代码报错
{attrs:{disabled:e.handleRowHandleButtonDisabled(e.rowHandle.edit.disabled,n.$index,n.row)}

**Comment by sunhaoxiang** [comment]
请更新2.1.1
