### ISSUE TITLE
能否提供远程加载数据的功能，和多种编辑模式的使用，这就更棒了！

### ISSUE THREAD

**Issue by 188007803** [d2-projects/d2-crud#5]
比如加上url属性，就可以从这个地址加载数据，并且可以自动分页等等。
编辑可以选择用：表单编辑，行内编辑，或单元格编辑。等等。

建议可以参考 miniui 的 datagrid 组件，里面的api，和效果非常丰富。
http://www.miniui.com/docs/api/index.html#ui=datagrid
http://www.miniui.com/demo/index.html#src=datagrid/celledit.html

**Comment by sunhaoxiang** [comment]
暂时没有集成远程加载数据功能的打算，你可以自己在D2 Crud的基础上封装一层网络请求供自己使用
