### ISSUE TITLE
D2 CRUD 模糊查询功能

### ISSUE THREAD

**Issue by AnnQian** [d2-projects/d2-crud#8]
D2 CRUD 模糊查询功能

功能是对表格字段能进行模糊查询，但是增加自定义文本框后会在标题和新增按钮外，布局实在太过奇葩|||，希望能嵌入模糊差查询文本框的位置

**Comment by sunhaoxiang** [comment]
暂时需要你自己在crud外部实现查询，近期没有计划添加查询的模块
