### ISSUE TITLE
表格列自定义组件传入参数问题

### ISSUE THREAD

**Issue by lamoce** [d2-projects/d2-crud#9]
表格列自定义组件传入参数目前是否只能传入由key参数定义的属性，而不能传入row对应的对象？
如果可以的话应该怎么实现啊？

**Comment by sunhaoxiang** [comment]
1.3.0已实现

**Comment by sunhaoxiang** [comment]
示例 https://d2admin.fairyever.com/#/demo/d2-crud/demo25
